workflows:
  ios-release:
    name: iOS Release - smartsave
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.smartsave.app
      vars:
        BUNDLE_ID: "com.smartsave.app"
      flutter: 3.38.7
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages get
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build IPA for distribution
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$($(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID" || echo 0) + 1) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        cancel_previous_submissions: true
        submit_to_app_store: false
      email:
        recipients:
          - mustafa.bilgic@student.auc.edu.tr
        notify:
          success: true
          failure: true

  android-release:
    name: Android Release - smartsave
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        BUNDLE_ID: "com.smartsave.app"
      flutter: 3.38.7
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages get
      - name: Build AAB
        script: |
          flutter build appbundle --release \
            --build-name=1.0.0 \
            --build-number=$PROJECT_BUILD_NUMBER
    artifacts:
      - build/app/outputs/bundle/**/*.aab
      - build/app/outputs/mapping/**/mapping.txt
    publishing:
      email:
        recipients:
          - mustafa.bilgic@student.auc.edu.tr
        notify:
          success: true
          failure: true
