workflows:
  ios-release:
    name: iOS Release - smartsave
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.smartsave.app
      vars:
        APP_STORE_CONNECT_ISSUER_ID: ${{APP_STORE_CONNECT_ISSUER_ID}}
        APP_STORE_CONNECT_KEY_IDENTIFIER: ${{APP_STORE_CONNECT_KEY_IDENTIFIER}}
        APP_STORE_CONNECT_PRIVATE_KEY: ${{APP_STORE_CONNECT_PRIVATE_KEY}}
        BUNDLE_ID: "com.smartsave.app"
      flutter: 3.38.7
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages get
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build IPA for distribution
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$((PROJECT_BUILD_NUMBER)) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        cancel_previous_submissions: true
        submit_to_app_store: false
      email:
        recipients:
          - dev@codemagic.io
        notify:
          success: true
          failure: true

  android-release:
    name: Android Release - smartsave
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - keystore_reference
      vars:
        BUNDLE_ID: "com.smartsave.app"
      flutter: 3.38.7
      groups:
        - google_play_credentials
        - app_store_credentials
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages get
      - name: Build AAB
        script: |
          flutter build appbundle --release \
            --build-name=1.0.0 \
            --build-number=$((PROJECT_BUILD_NUMBER))
    artifacts:
      - build/app/outputs/bundle/**/*.aab
      - build/app/outputs/mapping/**/mapping.txt
      - flutter_drive.log
    publishing:
      google_play:
        credentials: ${{GCLOUD_SERVICE_ACCOUNT_CREDENTIALS}}
        track: internal
        submit_as_draft: true
      email:
        recipients:
          - dev@codemagic.io
        notify:
          success: true
          failure: true